// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Body3bT8Nc-L5YpHwn3b3kI-S1YwulE',
    appId: '1:216377281095:web:4bb8c9e9e4ea9918107f62',
    messagingSenderId: '216377281095',
    projectId: 'evently-app-9fa88',
    authDomain: 'evently-app-9fa88.firebaseapp.com',
    storageBucket: 'evently-app-9fa88.firebasestorage.app',
    measurementId: 'G-X5SLH6WPJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8VMcH7E4XxinDarvv42SN-Wk4CGx6Z3U',
    appId: '1:216377281095:android:db1d80e3bd9e2a96107f62',
    messagingSenderId: '216377281095',
    projectId: 'evently-app-9fa88',
    storageBucket: 'evently-app-9fa88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjXdzu_J4x3bid-NWswDx5gsFF2Q30BXM',
    appId: '1:216377281095:ios:daad95e9c5c38d0d107f62',
    messagingSenderId: '216377281095',
    projectId: 'evently-app-9fa88',
    storageBucket: 'evently-app-9fa88.firebasestorage.app',
    iosClientId: '216377281095-8v3d8ug4pcaanrd9c0mdepbc24l5gq16.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1Body3bT8Nc-L5YpHwn3b3kI-S1YwulE',
    appId: '1:216377281095:web:fbafef38fde3b667107f62',
    messagingSenderId: '216377281095',
    projectId: 'evently-app-9fa88',
    authDomain: 'evently-app-9fa88.firebaseapp.com',
    storageBucket: 'evently-app-9fa88.firebasestorage.app',
    measurementId: 'G-B4KHVL4MM9',
  );

}